 я сделяль
ZalyalovIldar/HWCollectionView pull request #8
Opened 2016-11-21 13:19 UTC by Leklef

2016-11-21 21:07 UTC, ZalyalovIldar commented
Эхх вроде все ок, только после смены текста лейбла - падает приложение. Пробовал на разных, вроде везде падает. 
И посмотри свои лайауты у тебя много логов в консоль выводит 🎉

2016-11-21 21:08 UTC, ZalyalovIldar requested changes
Жду правки и ок :)

2016-11-22 06:15 UTC, Leklef commented
А вот и правки)

2016-11-23 21:42 UTC, ZalyalovIldar commented
нормас 👍

2016-11-23 21:42 UTC, ZalyalovIldar approved these changes

2016-11-23 21:42 UTC, closed without merging